### PR TITLE
Add onMapLoadedCallback which is invoked when the map has finished rendering

### PR DESCRIPTION
**Pull request by NicolasPoirier**

### CODE REVIEW

**Comment by JoanZapata** [comment]
`setOnMapLoadedCallback()` should immediately call the callback if the map is already loaded.

**Comment by NicolasPoirier** [comment]
Done

**Comment by JoanZapata** [comment]
As discussed, `mapAlreadyLoaded` should be set to `false` when the `TileRenderer` is set, so that a new callback can be set. 

Please add some documentation on `setMapLoadedCallback` and `OnMapLoadedCallback` interface to explicitly state that the callback is only called once, when all tiles of the current screen are rendered.

**Comment by NicolasPoirier** [comment]
I will change the name of the callback. It's not necessarily a map that we are rendering.

**Comment by JoanZapata** [comment]
Perfect thanks!

**Pull request merged**
